name: Build and Push Runner Images

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write
  checks: write

jobs:
  build-nitro-runner:
    runs-on: namespace-profile-default-arm64
    name: Build and Push Nitro runner image for ARM
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels, annotations) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/flashnetxyz/runner-images/nitro
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=sha
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./runners/nitro/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
